#!/bin/sh -e
FILES="bootcode.bin fixup.dat fixup_cd.dat fixup_x.dat kernel.img kernel7.img kernel_cutdown.img kernel_emergency.img start.elf start_cd.elf start_x.elf"

for FN in $FILES; do
  # Need to rm first to avoid error "rename involves overwriting ... with 
  # different file ..., not allowed
  rm -f /boot/$FN
  dpkg-divert --package rpikernelhack --remove --rename /boot/$FN
  sync
done


# Automatically added by dh_installmodules
if [ "$1" = "configure" ]; then
	if [ -e /boot/System.map-3.6.11+ ]; then
		depmod -a -F /boot/System.map-3.6.11+ 3.6.11+ || true
	fi
fi
# End automatically added section

